## Promise之前，解决异步方法
### callback
1) 有一个函数可以接收一个函数，可以根据条件选择执行这个函数
// 1.将函数作为函数的参数传递进去(回调)
// 传统的callback promise可以解决callback的问题
// lodash after async库 Promise.all  都有闭包的效果
```
function after (times,callback){
    return function(){
        times--;
        if(times == 0){
            callback();
        }
    }
}
let fn = after(3,function(){
    console.log('调用了三次 才执行的方法')
})
fn();
fn();
fn();
```
2) 读一个文件 3s后获得结果
 ```javascript
function read(calback){
	let r = 'hi'
	setTimeout(()=>{
		callback(r)
	})
}
read(function(result){
	console.log(result)
})
```
3) 文件读取
异步不支持try  catch
fs.readFile 第一个参数是路径，第二个是编码，第三个是回调，捕捉错误不能用try catch,可以在回调里放err.
```javascript
fs.readFile('1.txt','utf8',(err,data)=>{
	console.log(data)
})
```

4) 哨兵函数 see `callback2.js`

当函数满足某一条件时触发
```javascript
let school = {}
function out () {
	if((Object.keys(school)).length == 2){
		console.log(school)// 达到某一条件触发
	}
}
fs.readFile('1.txt','utf8',(err,data)=>{
	school.name = data
	out()
})
fs.readFile('2.txt','utf8',(err,data)=>{
	school.age = data
	out()
})
```
优化升级，次数可配置
```javascript
function after(times, callback) {
	return function() {
	    if(--times === 0){
    		callback(school)
    	}  
	}
}
let out =  after(3, function(data) {
	console.log(data)
})
```

### 发布订阅模式
> on emit 

> 发布订阅模式
- 先把需要订阅的内容保存到队列里
- 绑定事件 on 添加到队列 添加想触发的事件
- 触发emit, 可以自己控制触发条件
> 观察者模式 基于发布订阅 mvvm
```javascript
/**
 * Created by jyn on 2018/12/28.
 */
let fs = require('fs');
let school = {}

let Dep = {
	arr: [],
	on(fn){
		this.arr.push(fn)
	},
	emit(){
		// 达到预期再触发
		console.log('emit')
		if(Object.keys(school).length === 2){
			this.arr.forEach(function (fn) {
				console.log('emit!!')
				fn()
			})
		}
	}
}
Dep.on(function(){
	console.log(Dep.arr)
})
Dep.on(function(){
	console.log(Dep.arr)
})

fs.readFile('1.txt','utf8',(err,data)=>{
	school.name = data
	Dep.emit()
})
fs.readFile('2.txt','utf8',(err,data)=>{
	school.age = data
	Dep.emit()
})
```
## promise出来了
+ 解决回调地狱
+ 多个异步请求在同一s时间合并结果

promise使用时，需要 new Promise

- promise 就是一个类型
- new Promise时需要传递一个executor执行器（同步执行的）
- executor中有两个参数 resolve成功 reject失败
- 每个promise上都有then方法 then方法中有两个函数 成功函数 失败函数
- promise三个状态 pending resolve reject

关于then
+ then方法执行完会判断返回的结果，如果是promise,会把这个promise执行，h会取到它的结果；
+ 每次调用then方法后，会再返回一个新的promise 并不是this
+ 链式调用解决回调嵌套问题
+ promise失败后如果then中没有失败函数，错误没有捕获，会走最后的catch,中间then处理过错误，就不会被catchx再捕获
+ then中返回promise,会把promise的结果作为下一个then的参数，如果返回一个普通值，会作为下一次then成功的结果
+ then方法执行抛出了异常（`return Promise.reject()`或者`throw new Error('error')`），会走下一次then的失败的回调 

```javascript

function read(filePath,encoding){
    return new Promise((resolve,reject)=>{
        fs.readFile(filePath,encoding,(err,data)=>{
            if(err) reject(err);
            resolve(data);
        });
    })
}
```
## promise链式调用

### promise 实现
```javascript
function Promise(executor){
    // executor是立即执行
    let self = this;
    self.value = undefined;//保存成功的值和失败的原因
    self.reason = undefined;
    self.status = 'pending';
    self.onResolvedCallbacks = [];// 存放then中成功的回调
    self.onRejectedCallbacks = []; // 存放then中失败的回调
    function resolve(value){
        if(self.status === 'pending'){
            self.value = value;
            self.status = 'resolved';
            self.onResolvedCallbacks.forEach(fn=>fn());
        }
    }
    function reject(reason){
        if(self.status === 'pending'){
            self.reason = reason;
            self.status = 'rejected';
            self.onRejectedCallbacks.forEach(fn=>fn());
        }
    }
    // 如果函数执行时发生异常 就走到失败中
    try{
        executor(resolve,reject);
    }catch(e){
        reject(e);
    }
}
// then是实例中的方法
Promise.prototype.then = function(onFulfilled,onRejected){
    let self = this;
    if(self.status === 'resolved'){
        onFulfilled(self.value);
    }
    if(self.status === 'rejected'){
        onRejected(self.reason);
    }
    if(self.status === 'pending'){
        // 异步实现
        // 保存回调函数
        self.onResolvedCallbacks.push(()=>{
            onFulfilled(self.value);
        });
        self.onRejectedCallbacks.push(()=>{
            onRejected(self.reason)
        });
    }
}
module.exports = Promise;
```
test
```javascript
let Promise = require('./1.promise')
// 成功和失败的时候可以传递参数 (成功和失败是你自己定义的)
let promise = new Promise((resolve,reject)=>{
    reject();
});
promise.then((data)=>{
    console.log('success'+data)
},(err)=>{
    console.log('error'+err)
})
promise.then((data)=>{
    console.log('success'+data)
},(err)=>{
    console.log('error'+err)
})
```

优化：调用then后返回一个新的promise
```javascript
// then调用的时候 都是异步调用 (原生的then的成功或者失败 是一个微任务)
Promise.prototype.then = function (onFulfilled, onRejected) {
    // 成功和失败的回调 是可选参数
    
    // onFulfilled成功的回调 onRejected失败的回调
    let self = this;
    let promise2;
    // 需要没次调用then时都返回一个新的promise
    promise2 = new Promise((resolve, reject) => {
        if (self.status === 'resolved') {
            setTimeout(()=>{
                try {
                    // 当执行成功回调的时候 可能会出现异常，那就用这个异常作为promise2的错误的结果
                    let x = onFulfilled(self.value);
                    //执行完当前成功回调后返回结果可能是promise
                    resolvePromise(promise2,x,resolve,reject);
                } catch (e) {
                    reject(e);
                }
            },0)
        }
        if (self.status === 'rejected') {
            setTimeout(()=>{
                try {
                    let x = onRejected(self.reason);
                    resolvePromise(promise2,x,resolve,reject);
                } catch (e) {
                    reject(e);
                }
            },0)
        }
        if (self.status === 'pending') {
            self.onResolvedCallbacks.push(() => {
                setTimeout(()=>{
                    try {
                        let x = onFulfilled(self.value);
                        resolvePromise(promise2,x,resolve,reject);
                    } catch (e) {
                        reject(e);
                    }
                },0)
            });
            self.onRejectedCallbacks.push(() => {
                setTimeout(()=>{
                    try {
                        let x = onRejected(self.reason);
                        resolvePromise(promise2,x,resolve,reject);
                    } catch (e) {
                        reject(e);
                    }
                },0)
            });
        }
    });
    return promise2
}
```
### 关于promise a+ 2.3 the promise resolution procesure
> x是thenable，即x为promise
```javascript
function resolvePromise(promise2,x,resolve,reject){
    if(promise2 === x){
        // 自己不能等待自己完成
        return reject(new TypeError('Chaining cycle'));
    } 
    let called;
    // 判断x是不是promise
    if(x!==null && (typeof x=== 'object' || typeof x === 'function')){
        try{
            let then = x.then; 
            // then是函数，才是真正的promise
            if(typeof then === 'function'){
                then.call(x,y=>{ 
                    if(called) return; 
                    called = true;
                    resolvePromise(promise2,y,resolve,reject);
                },err=>{ 
                    if(called) return;
                    called = true;
                    reject(err);
                });// x.then(()=>{},()=>{})
            }else{
                resolve(x);
            }
        }catch(e){
            if(called) return;
            called = true;
            reject(e);
        }
    }else{ 
        resolve(x);
    }
}
```

### test
`
npm install promises-aplus-tests -g 
`

```javascript
Promise.defer =  Promise.deferred = function() {
	let dfd = {}
	dfd.promise = new Promise((resolve, reject) => {
		dfd.resolve = resolve
		dfd.reject = reject
	})
	return dfd
}
```

```javascript 
// 测试命令
promises-aplus-tests promise.js
```